<<<<<<< HEAD
# Site settings
title: Whb
email:whb@bupt.edu.cn
description:灬丶斌 视野
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Gaohaoyang
=======
# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:https://snailwhb.github.io/
date_format: "ordinal"
title: 灬丶斌 视野
subtitle: Snail
description: "斌博客"                    
keywords: 视野, Wang huobin,Snail 
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wang huobin
organization: Bupt, School.
location: Beijing, China
email: whb@bupt.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /blog/
    label: 博客
    
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
>>>>>>> origin/master
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false

theme: jekyll-theme-dinky